paneru.setup({
	options = { preset_column_widths = { 0.3, 0.5, 0.7, 1 }, sliver_width = 1 },
	padding = { left = 10, right = 10 },
	swipe = { gesture = { fingers_count = 3, vertical = true } },
	bindings = {
		["window focus north"] = "alt - p",
		["window focus south"] = "alt - n",
		["window focus west"] = "alt - a",
		["window focus east"] = "alt - e",
		["window swap west"] = "alt - b",
		["window swap east"] = "alt - f",
		["window stack"] = "alt - i",
		["window unstack"] = "alt - o",
		["window grow"] = "alt - r",
		["window shrink"] = "alt - s",
		["window center"] = "alt - c",
		["window manage"] = "alt - m",
		["window togglefloatlayer"] = "alt - t",
		["window virtualnum 1"] = "alt - 1",
		["window virtualnum 2"] = "alt - 2",
		["window virtualnum 3"] = "alt - 3",
		["window virtualmovenum 1"] = "alt + shift - 1",
		["window virtualmovenum 2"] = "alt + shift - 2",
		["window virtualmovenum 3"] = "alt + shift - 3",
	},
	decorations = { inactive = { dim = { opacity = -0.1, opacity_night = -0.1 } } },
	restore = { enabled = true, startup_grace_ms = 2000 },
	windows = {
		all = { title = ".*", vertical_padding = 20, horizontal_padding = 10 },
		colors = { title = "^Colors$", floating = true },
		fonts = { title = "^Fonts$", floating = true },
		facetime = { title = ".*", bundle_id = "com.apple.Facetime", floating = true },
		devicehub = { title = ".*", bundle_id = "com.apple.dt.Devices", floating = true },
		iina = { title = ".*", bundle_id = "com.colliderli.iina", floating = true },
	},
})
