duti -s org.gnu.Emacs public.json all
duti -s org.gnu.Emacs public.plain-text all
duti -s org.gnu.Emacs public.python-script all
duti -s org.gnu.Emacs public.shell-script all
duti -s org.gnu.Emacs public.source-code all
duti -s org.gnu.Emacs public.text all
duti -s org.gnu.Emacs public.unix-executable all
# this works for files without a filename extension
duti -s org.gnu.Emacs public.data all

duti -s org.gnu.Emacs .c all
duti -s org.gnu.Emacs .cpp all
duti -s org.gnu.Emacs .cs all
duti -s org.gnu.Emacs .css all
duti -s org.gnu.Emacs .go all
duti -s org.gnu.Emacs .java all
duti -s org.gnu.Emacs .js all
duti -s org.gnu.Emacs .sass all
duti -s org.gnu.Emacs .scss all
duti -s org.gnu.Emacs .less all
duti -s org.gnu.Emacs .vue all
duti -s org.gnu.Emacs .cfg all
duti -s org.gnu.Emacs .json all
duti -s org.gnu.Emacs .jsx all
duti -s org.gnu.Emacs .log all
duti -s org.gnu.Emacs .lua all
duti -s org.gnu.Emacs .md all
duti -s org.gnu.Emacs .php all
duti -s org.gnu.Emacs .pl all
duti -s org.gnu.Emacs .py all
duti -s org.gnu.Emacs .rb all
duti -s org.gnu.Emacs .ts all
duti -s org.gnu.Emacs .tsx all
duti -s org.gnu.Emacs .txt all
duti -s org.gnu.Emacs .conf all
duti -s org.gnu.Emacs .yaml all
duti -s org.gnu.Emacs .yml all
duti -s org.gnu.Emacs .toml all
